services:
  dca-service:
    image: ghcr.io/zuricos/dotnet-kraken-dca-bot/dca-service:1.2.1
    container_name: dca-service
    restart: unless-stopped
    secrets:
      - dca-secrets
    volumes:
      - state:/app/state:rw
      - logs:/app/logs:rw
    env_file:
      - stack.env

  mail-service:
    image: ghcr.io/zuricos/dotnet-kraken-dca-bot/mail-service:1.2.1
    container_name: mail-service
    restart: unless-stopped
    secrets:
      - mail-secrets
    volumes:
      - state:/app/state:rw
      - logs:/app/logs:rw
    env_file:
      - stack.env

  kraken-database:
    image: postgres:latest
    container_name: kraken-database
    env_file:
      - stack.env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

secrets:
  dca-secrets:
    file: /home/{user}/{dir}/docker.dca.secrets.json
  mail-secrets:
    file: /home/{user}/{dir}/docker.mail.secrets.json

volumes:
  pg_data:
  state:
  logs:
